name: CI
permissions:
  contents: read
on:
  pull_request:
  push:
    branches:
      - "*main"
env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  ci:
    permissions:
      contents: none
    name: CI
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  build:
    name: Build
    strategy:
      matrix:
        build: [linux, windows]
        include:
        - build: linux
          os: ubuntu-latest
          rust: "stable"
          features: "full"
        - build: windows
          os: windows-latest
          rust: "stable"
          features: "full"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release
      
